### ISSUE TITLE
Issues joining game

### ISSUE THREAD

**Issue by M47HATT3R** [avimoondra/fishbowl#107]
Once more than 3/4 people try to join a room the option to join no longer shows up and you can only take the place of someone already in the game.
You can only see a "change" button that'll change a current players name but not join the game.

**Comment by avimoondra** [comment]
@M47HATT3R is this still happening for you? I haven't heard any other reports - so this is definitely curious. mind sharing some screenshots when you get the chance?

**Comment by jbkimble** [comment]
@avimoondra Hello! I play fishbowl once a week with a group of 4-8 people, we played weekly for 6ish weeks and then ultimately encountered this problem which derailed us from playing for several weeks. Ultimately **the solution was everyone had to clear their browser data to get it to work again**.

Perhaps it is only a bug that arrises when users have been playing for a large number of rounds? Also thank you for this game,  it is very well done and it has brought a lot of happiness, joy, and connection to my family and friends during the pandemic!
