### ISSUE TITLE
Predefined card list

### ISSUE THREAD

**Issue by mmoylan** [avimoondra/fishbowl#108]
Hi, I know fishbowl is meant to be played with submissions from each player.  But I am a teacher and want to do it as a virtual review game with a predefined set of vocabulary.  Could 0 submissions be added, and the ability for the host to provide all the words.

**Comment by avimoondra** [comment]
@mmoylan 

Coming soon! I like the idea of host providing words, originally was going to provide those predefined lists, like Pokemon, Celebrities, etc. But I see the possibility of both.

I think it'd be great to have a "For Teachers" section that explains various features for teachers (e.g. screening cards). For your use case, an option might be to have students submit some words (from a vocabulary or topic provided) and you can screen them as a host.

<img width="550" alt="Screen Shot 2020-10-30 at 10 49 12 AM" src="https://user-images.githubusercontent.com/2534903/97719786-e0e19580-1a9d-11eb-8187-f78f8dc24829.png">

**Comment by avimoondra** [comment]
@mmoylan Your feature request is now available :) 

Let me know how it works out for you (and other teachers!)

![image](https://user-images.githubusercontent.com/2534903/101234725-c2b81800-368f-11eb-9ff1-5d407d1f2790.png)

![image](https://user-images.githubusercontent.com/2534903/101234734-cf3c7080-368f-11eb-9336-507c249573c3.png)
