### ISSUE TITLE
Upper bound on number of players?

### ISSUE THREAD

**Issue by ankitvgupta** [avimoondra/fishbowl#118]
Is there any guidance on how many players this can support? Looking to use it for 20-30 people in a group - any reason to believe that wouldn't work?

**Comment by avimoondra** [comment]
@ankitvgupta there's no upper limit! It has definitely supported 30 players in the past.

I think the game's social experience, however, is best in the 10-15 range. So you may consider splitting your group in 2 if possible! Let me know how it works out.

**Comment by ankitvgupta** [comment]
Thanks! We ended up having 25 or so and it worked without a hitch. Appreciate the input!

**Comment by avimoondra** [comment]
@ankitvgupta Great to hear !!
