### ISSUE TITLE
Limit username length

### ISSUE THREAD

**Issue by TulioAbreu** [avimoondra/fishbowl#143]
It seems username is not limited, or its current limit is too long. 

![image](https://user-images.githubusercontent.com/33965580/143626588-18a8d2e7-af29-4ada-a769-9a16e6f134f7.png)

It would be nice to set a limit

**Comment by BlockArchitech** [comment]
Hey there! Just submitted #152 which fixes this.

**Comment by avimoondra** [comment]
Resolved! Thanks @TulioAbreu  for the feedback, and @BlockArchitech  for the fix!
