### ISSUE TITLE
GraphQL error : unable to host a game 

### ISSUE THREAD

**Issue by Natelegreat1** [avimoondra/fishbowl#31]
<img width="1386" alt="Screen Shot 2020-05-05 at 3 35 14 PM" src="https://user-images.githubusercontent.com/2666640/81108423-adef8800-8ee6-11ea-8745-efcae6e2b3a3.png">

When clicking on HOST GAME, it simply reloads the page :(

**Comment by avimoondra** [comment]
@Natelegreat1 sorry about this! Should be fixed now (as of 1:14 PM PST) - was due to not updating the "allowed queries" list.

**Comment by avimoondra** [comment]
@Natelegreat1 lmk if it works for you? If so, I'll close out this issue. Thanks for reporting.

**Comment by Natelegreat1** [comment]
@avimoondra looking good! Love the site. You're great. I hope to be able to help with your amazing list of new features on Trello when I get some free time <3

**Comment by avimoondra** [comment]
@Natelegreat1 Great! Appreciate that 🙇 

Awesome - join us whenever in [this Slack group](https://join.slack.com/t/fishbowl-game/shared_invite/zt-dzi7puk6-Dpcg748SKqoBeRqZOfV7~g)!
