### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jasrys** [avimoondra/fishbowl#6]
Thanks for making this. Was working on a similar thing for my family/friends.

What license is this being released under?

**Comment by avimoondra** [comment]
@jasrys awesome. And thanks for flagging this - will upload a license shortly!

**Comment by avimoondra** [comment]
Started out with MIT, https://github.com/avimoondra/fishbowl/commit/666bd764e9d196a01cb0d5eadefa206b85d74f6b. Thanks again for opening an issue for this @jasrys
